services:
  file-converter:
    networks:
      - hawki-network
      - default
  file-converter-worker:
    networks:
      - hawki-network
      - default
networks:
  hawki-network:
    name: hawki-network
    external: true
