services:
  file-converter:
    environment:
      ## Some space for local test envs
      # - SAVE_DOCUMENT_IMAGE_REFS=true
      # - OCR_LANGUAGES=en,de
    networks:
      - hawki-network
      - default
networks:
  hawki-network:
    name: hawki-network
    external: true
