networks:
  hawki-network:
    driver: bridge

services:
  file-converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - F_API_KEY=${F_API_KEY:-}
      - POSTGRES_ENABLED=${POSTGRES_ENABLED:-true}
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL:-postgresql+asyncpg://prefect@127.0.0.1:5432/prefect}
    restart: unless-stopped
