networks:
  hawki-network:
    driver: bridge

services:
  file-converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - F_API_KEY= ${F_API_KEY:-} # Empty by default
    restart: unless-stopped
