log:
    stdout: true
    level: info
    levelCore: error

persistence:
    numHistoryShards: 4
    defaultStore: default
    visibilityStore: visibility
    datastores:
        default:
            sql:
                pluginName: "postgres12"
                databaseName: "temporal"
                connectAddr: "127.0.0.1:5432"
                connectProtocol: "tcp"
                user: "temporal"
                password: ""
                maxConns: 20
                maxIdleConns: 20
                maxConnLifetime: 1h
        visibility:
            sql:
                pluginName: "postgres12"
                databaseName: "temporal_visibility"
                connectAddr: "127.0.0.1:5432"
                connectProtocol: "tcp"
                user: "temporal"
                password: ""
                maxConns: 10
                maxIdleConns: 10
                maxConnLifetime: 1h

global:
    membership:
        maxJoinDuration: 30s
        broadcastAddress: "127.0.0.1"
    pprof:
        port: 7936

services:
    frontend:
        rpc:
            grpcPort: 7233
            membershipPort: 6933
            bindOnIP: "0.0.0.0"
            httpPort: 7243
    matching:
        rpc:
            grpcPort: 7235
            membershipPort: 6935
            bindOnLocalHost: true
    history:
        rpc:
            grpcPort: 7234
            membershipPort: 6934
            bindOnLocalHost: true
    worker:
        rpc:
            membershipPort: 6939

clusterMetadata:
    enableGlobalNamespace: false
    failoverVersionIncrement: 10
    masterClusterName: "active"
    currentClusterName: "active"
    clusterInformation:
        active:
            enabled: true
            initialFailoverVersion: 1
            rpcName: "frontend"
            rpcAddress: "localhost:7233"
            httpAddress: "localhost:7243"

dcRedirectionPolicy:
    policy: "noop"

