[program:prefect-server]
command=/container/bin/start-prefect-server.sh
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
