[program:temporal-server]
command=/container/bin/start-temporal-server.sh
directory=/etc/temporal
user=root
autostart=true
autorestart=true
priority=20
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
